### ISSUE TITLE
build error. : 'CodeStylePageWidget' in namespace 'Go::Ui' does not name a type

### ISSUE THREAD

**Issue by gonboy** [gotschmarcel/qtcreator-go#2]
1.  Qt5.8.0, mingw , the latest QtCreator.
    2.  build qtcreator-go
    3.  error is :100: 
```
In file included from ..\..\..\goplugin.cpp:29:0:
..\..\..\settings/gocodestylepage.h:25:9: error: 'CodeStylePageWidget' in namespace 'Go::Ui' does not name a type
     Ui::CodeStylePageWidget *_ui;
```
may bacase is:
```
namespace Go {
namespace Ui {
    class BuildNRunSettingsPageWidget: public Ui_BuildNRunSettingsPageWidget {};
} // namespace Ui
} // namespace Go
```

**Comment by gonboy** [comment]
change it to ' <class>Go::CodeStylePageWidget</class>'
build ok

**Comment by gonboy** [comment]
But the plugin , maybe couldn't run.

**Comment by gotschmarcel** [comment]
If you remove the `Ui::` then you're actually referring to the class itself, which is not what this is supposed to be. You should try `::Ui::CodeStylePageWidget`. I'll fix it as soon as I can.

**Comment by gonboy** [comment]
OK. TEST OK.
