### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by sulthonzh** [gotschmarcel/qtcreator-go#5]
Hi Bro, can you tell about this? where ui_buildnrunsettingspagewidget.h:?
/home/{user}/Documents/project/qt/qtcreator-go/settings/gobuildnrunsettingspage.h:8: error: ui_buildnrunsettingspagewidget.h: No such file or directory

**Comment by gotschmarcel** [comment]
Hi, I fixed the issue. Sorry for the inconvenience!

**Comment by sulthonzh** [comment]
@gotschmarcel thanks very much for your response, :)
